### PR TITLE
Migrate to Xcode 10 and Swift 4.2

### PR DESCRIPTION
**Pull request by mjarvis**
Updates Framework, Tests, and Example targets to build using Swift 4.2 in Xcode 10

### CODE REVIEW

**Comment by XavierDK** [comment]
May we merge it and create a new release please?

**Comment by gabrielapittari** [comment]
Any updates on this? Thanks :)

**Comment by bryanjclark** [comment]
This looks terrific, thanks!

**Comment by wdcurry** [comment]
Indeed, 25 compile issues on my first test.  Any updates? Any recommended forks?

**Comment by mjarvis** [comment]
@wdcurry https://github.com/Khan/SwiftTweaks/releases/tag/v.4.0.1 was released back in october, which included these changes. What version are you using? & what version Xcode/Swift?

**Comment by mjarvis** [comment]
@wdcurry Oh, I'm sorry! looks like it was never released to CocoaPods. CC @bryanjclark to please push a release. https://github.com/Khan/SwiftTweaks/issues/119

**Pull request merged**
