### PR TITLE
Swift3 support

### PR DESCRIPTION
**Pull request by yarneo**

### CODE REVIEW

**Comment by NachoSoto** [comment]
Did you see #63?

**Comment by yarneo** [comment]
I did, it crashed on my end. I preferred to do it from scratch with manual conversion rather than automatic xcode conversion. You don't have to use it if you don't want to!

**Comment by bryanjclark** [comment]
Let's close this one out since we're working on this in #63

**Comment by bryanjclark** [comment]
(that said, thanks @yarneo for your submission! :1 )

**Pull request closed without merging**
